config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'friendships/create'
  post 'friendships/update', to: 'friendships#update'
  get 'friendships/destroy'
  post 'friendships/create', to: 'friendships#create'
  get 'likes/new'
  post 'likes/create', to: 'likes#create'
  get 'likes/destroy'
  get 'comments/new'
  get 'comments/create'
  # devise_for :users, controllers: {
  #       sessions: 'users/sessions'
  #     }

  post '/search', to: 'users#search'
  get '/search', to: 'posts#index'

  get 'users/show'
  get '/notifications', to: 'users#notifications'
  get 'users/:id/notifications', to: 'users#notifications'
  get '/all_friends', to: 'users#all_friends'
  get 'users/:id/all_friends', to: 'users#all_friends'
  get 'posts/show'
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end
    unauthenticated :user do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  get 'pages/home'
  resources :users
  resources :posts
  resources :comments
  resources :likes
  resources :friendships
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts
  has_many :comments
  has_many :likes
  has_many :friendships
  has_many :friends, through: :friendships

  has_attached_file :avatar

  validates_attachment_content_type :avatar, content_type: ['image/jpg', 'image/jpeg', 'image/png']

  def full_name
    "#{first_name} #{last_name}"
  end

  def friend_with?(user)
    if friendships.find_by(friend_id: user.id)

      friendships.find_by(friend_id: user.id).status == 'active'
    elsif user.friendships.find_by(friend_id: id)
      user.friendships.find_by(friend_id: id).status == 'active'
    else
      false
    end
  end

  def pending_friendship_with?(user)
    if friendships.find_by(friend_id: user.id)
      return true if friendships.find_by(friend_id: user.id).status == 'pending'
   end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :date_of_birth, :gender, :password, :email, :current_password])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_only

  def index
    @users = User.all.paginate(page: params[:page], per_page: 20)
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def search
    @users = User.where(first_name: search_params[:first_name]).or(User.where(last_name: search_params[:first_name])).or(User.where(email: search_params[:first_name]))
    if !@users.empty?
      flash.now[:success] = 'User(s) found'
    else
      flash.now[:warning] = 'Not found'
  end
  end

  def all_friends
    @direct_friendships  = Friendship.where(friend_id: current_user.id).where(status: 'active').map(&:user_id)

    @inverse_friendships = Friendship.where(user_id: current_user.id).where(status: 'active').map(&:friend_id)

    all_friends_ids = @direct_friendships.concat(@inverse_friendships)

    @friends = User.where(id: all_friends_ids).paginate(page: params[:page], per_page: 10)
  end

  def notifications
    @pending_friendships = Friendship.where(friend_id: current_user.id).filter { |friendship| friendship.status == 'pending' }
  end

  private

  def search_params
    params.require(:user).permit(:first_name)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/all_friends.html.erb
<h2>Friends</h2>
<% if @friends.any?  %>
<%= will_paginate @friends %>
<% @friends.each do |friend| %>
   <p> <%= profile_picture friend %></p>
   <p> <%= link_to "#{friend.full_name}", friend %></p>
<% end %>
 <% else %>
 <p>No friends available </p>
 <% end %> 
 

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <h2>Make Changes To Your Profile</h2>

<%= form_for(@user, url: registration_path(@user), html: { method: :put }) do |f| %>

    <div class="form-group form-group-lg">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true, autocomplete: "", class:"form-control" %>
  </div>

  <div class="form-group form-group-lg">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, autofocus: true, autocomplete: "", class:"form-control"%>
  </div>

  <div class="form-group form-group-lg">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control" %>
  </div>


  <% if @user.confirmed_at == nil || @user.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= @user.email %></div>
  <% end %>

  <div class="form-group form-group-lg">
    <%= f.label :date_of_birth %><br />
    <%= f.date_field :date_of_birth, autofocus: true, autocomplete: "", class:"form-control" %>
  </div>
  <div class="form-group form-group-lg">
    <%= f.label :gender %><br />
    <%= f.text_field :gender, autofocus: true, autocomplete: "", class:"form-control" %>
  </div>

  <div class="form-group form-group-lg">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "new-password", class:"form-control" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="form-group form-group-lg">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" , class:"form-control"%>
  </div>

  <div class="form-group form-group-lg">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "current-password", class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Update", class:"btn btn-success btn-lg update-button" %>
  </div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= button_to "Cancel my account", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %></p>

<%= link_to "Back", :back %>
  </div>
</div>

app/views/users/index.html.erb
<h2>Users</h2>
<%= will_paginate %>
<% @users.each do |user| %> 
    <% if user == current_user %>
    <p><%= profile_picture user%></p>
    <p>
    <strong><%= link_to "#{user.full_name}", user %></strong>
     </p>
     <% elsif current_user.friend_with?(user) %>
     <p><%= profile_picture user%></p>
     <p>
      <strong><%= link_to "#{user.full_name}", user %></strong>
      <%= link_to "Unfriend", friendships_destroy_path(friend_id:user),method: :delete, data: {confirm: "Are you sure you want to unfriend this user?"} %>
      </p>
      <% elsif current_user.pending_friendship_with?(user) %>
      <p><%= profile_picture user%></p>
     <p>
     
     <strong><%= link_to "#{user.full_name}", user %></strong>
      Pending Request
      <%= link_to "Delete_Request", friendships_destroy_path(friend_id:user),method: :delete, data: {confirm: "Are you sure you want to remove this request?"}%>
      </p>
      <% else %>
      <p><%= profile_picture user%></p>
      <p>
      <strong><%= link_to "#{user.full_name}", user %></strong>
      <%= link_to "Add Friend", friendships_create_path(friend_id:user),method: :post  %>
      </p>
      <% end %>
   <% end %>
   <%= will_paginate %>
  

app/views/users/notifications.html.erb
<% if @pending_friendships.any? %>
 <p>There are <%= pluralize(@pending_friendships.count, 'request')%> pending... </p>
  <% @pending_friendships.each do |pending| %>
    <p><%= profile_picture pending.user%></p>
    <p>
  <%= link_to "#{pending.user.full_name}", pending.user %>  
  <%= link_to "Confirm friendship", friendships_update_path(user_id:pending.user.id),method: :post%>

  <%= link_to "Decline Friendship", friendships_destroy_path(friend_id:pending.user.id),method: :delete, data: {confirm: "Are you sure you want to decline this request?"} %>
  </p> 

  <% end %>
  <% else %>


  <p>There are no pending friend requests </p>
  <% end %>

app/views/users/search.html.erb
<h2>Search Results</h2>

<% @users.each do |user| %> 
    <% if user == current_user %>
    <p><%= profile_picture user%></p>
    <p>
    <strong><%= link_to "#{user.full_name}", user %></strong>
     </p>
     <% elsif current_user.friend_with?(user) %>
     <p><%= profile_picture user%></p>
     <p>
      <strong><%= link_to "#{user.full_name}", user %></strong>
      <%= link_to "Unfriend", friendships_destroy_path(friend_id:user),method: :delete, data: {confirm: "Are you sure you want to unfriend this user?"} %>
      </p>
      <% elsif current_user.pending_friendship_with?(user) %>
      <p><%= profile_picture user%></p>
     <p>
     
      <strong><%= link_to "#{user.full_name}", user %></strong>
      Pending Request
      <%= link_to "Delete_Request", friendships_destroy_path(friend_id:user),method: :delete, data: {confirm: "Are you sure you want to remove this request?"}%>
      </p>
      <% else %>
      <p><%= profile_picture user%></p>
      <p>
      <strong><%= link_to "#{user.full_name}", user %></strong>
      <%= link_to "Add Friend", friendships_create_path(friend_id:user),method: :post  %>
      </p>
      <% end %>
   <% end %>

  

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3 user-profile">
    <p> 
      <%= profile_picture @user %> 

    </p>
    <%= link_to "#{@user.full_name}", @user %>

    <% if @user == current_user %>

    <% elsif current_user.friend_with?(@user) %>
      <%= link_to "Unfriend", friendships_destroy_path(friend_id:@user),method: :delete, data: {confirm: "Are you sure you want to unfriend this user?"} %>
    <% elsif current_user.pending_friendship_with?(@user) %>
      <%= link_to "Delete_Request", friendships_destroy_path(friend_id:@user),method: :delete, data: {confirm: "Are you sure you want to remove this request?"}%>
    <% else %>
      <%= link_to "Add Friend", friendships_create_path(friend_id:@user),method: :post  %>
    <% end %>
  </div>


  <div class="col-md-6">

    <% if current_user.friend_with?(@user) || current_user == @user %>
      <%= render './shared/post_new_form'  %>
    <% end %>
    
    <h4>
      All Post (<%= @user.posts.count %>)
    </h4>

    <%= render './shared/feed' %>

  </div>
</div>