config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'friendships/create'
  post 'friendships/update', to: 'friendships#update'
  get 'friendships/destroy'
  post 'friendships/create', to: 'friendships#create'
  get 'likes/new'
  post 'likes/create', to: 'likes#create'
  get 'likes/destroy'
  get 'comments/new'
  get 'comments/create'
  # devise_for :users, controllers: {
  #       sessions: 'users/sessions'
  #     }

  post '/search', to: 'users#search'
  get '/search', to: 'posts#index'

  get 'users/show'
  get '/notifications', to: 'users#notifications'
  get 'users/:id/notifications', to: 'users#notifications'
  get '/all_friends', to: 'users#all_friends'
  get 'users/:id/all_friends', to: 'users#all_friends'
  get 'posts/show'
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end
    unauthenticated :user do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  get 'pages/home'
  resources :users
  resources :posts
  resources :comments
  resources :likes
  resources :friendships
end

app/views/shared/_feed.html.erb
<% if @posts.any? %>
      <% @posts.each do |post| %>
    
        <div class = "well">
          <div class="row">
            <div class="col-md-2">

              <%= profile_picture post.user %>
            </div>

            <div class="col-md-10 comment-body">
              <p><%= link_to  "#{post.user.full_name}", post.user  %></p>
              <span class="timestamp">
                <%= time_ago_in_words(post.created_at) %> ago.
              </span>
            </div>
          </div>

          <p class = "post-content"> <%= post.content %> </p>
          <p> <%= image_tag post.image.url(:large) if post.image? %> </p>

          <div class="post-padding">
            <% if post.likes.any? %>
              <span> <%= pluralize( post.likes.count, 'like') %> </span>
            <% end %>
            <% if current_user.likes.include?(Like.where(likeable_id: post.id).find_by(likeable_type: "Post")) %>
     
              <%= link_to 'unlike', likes_destroy_path(likeable_type: "Post", likeable_id: post.id), method: :delete %>
  
            <% else %>
  
              <%= link_to 'like', likes_create_path(likeable_type: "Post", likeable_id: post.id), method: :post %>
  
            <% end %>
        
          </div>
     

     
    
          <% if post.comments.any? %>

            <% post.comments.each do |comment| %>
              <div class="row comment-top-margin">
                <div class="col-md-2">
                  <%= profile_picture comment.user %>
                </div>
      
                <div class="col-md-10 comment-body">
               
                  <p><%= link_to  "#{comment.user.full_name}", comment.user  %> <%= comment.body %></p>
                  <span class="timestamp">
                    <%= time_ago_in_words(comment.created_at) %> ago.
                  </span>
                  <span class="likes">
                    <% if comment.likes.any? %>
                      <span> <%= pluralize( comment.likes.count, 'like') %> </span>
                    <% end %>

                    <% if current_user.likes.include?(Like.where(likeable_id: comment.id).find_by(likeable_type: "Comment")) %>
          
                      <%= link_to 'unlike', likes_destroy_path(likeable_type: "Comment", likeable_id: comment.id), method: :delete %>
        
                    <% else %>
        
                      <%= link_to 'like', likes_create_path(likeable_type: "Comment", likeable_id: comment.id), method: :post %>
        
                    <% end %>
                  </span>
                </div>
             
              </div>
        
            <% end %>
       
          <% end %>
          
       
          <div class="row">
            <div class="col-md-2">
              <%= profile_picture current_user %>
            </div>
            <div class="col-md-10 comment-body ">
              <%= form_for (Comment.new), html: {class: "comment-form-inline form-inline "} do |f| %>
           
                <%= f.text_field :body, class:"form-control input-lg comment-input",placeholder: "Write a comment..." %>
                <%= f.hidden_field :post_id, value: post.id%>
            
                <%= f.submit "Comment", class:"btn-comment" %>
              <% end %>
            </div>
          </div>
    
        </div>
    
      <% end %>

    <% end %>

app/views/shared/_new_comment_form.html.erb
<%= form_for (Comment.new) do |f| %>
      <%= f.text_field :body%>
      <%= f.hidden_field :post_id, value: post.id %>
      <%= f.submit "Comment" %>
    <% end %>

app/views/shared/_post_new_form.html.erb
<div class="well">
<%= form_for (Post.new) do |f| %>

<%= f.text_area :content, placeholder:"Create post" %>

    <%= f.file_field :image %>
<%= f.submit "Create Post",class:"btn btn-default btn-post" %>

<% end %>
</div>

<script type="text/javascript">
  $('#post_image').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 1) {
      alert('Maximum file size is 1MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_signin_form.html.erb
<%= form_for :user, :url => session_path(:user), html: {class: "form-inline", role:"form"} do |f| %>
  
    <div class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "current-password",class:"form-control" %>
  </div>
  <div class="form-group">
   <br />
    <%= f.submit "Log in", class:"btn btn-primary"  %>
    </div>
<% end %>

<%= link_to "Forgot your password?", new_password_path(:user), class: 'light-color'%>