config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'friendships/create'
  post 'friendships/update', to: 'friendships#update'
  get 'friendships/destroy'
  post 'friendships/create', to: 'friendships#create'
  get 'likes/new'
  post 'likes/create', to: 'likes#create'
  get 'likes/destroy'
  get 'comments/new'
  get 'comments/create'
  # devise_for :users, controllers: {
  #       sessions: 'users/sessions'
  #     }

  post '/search', to: 'users#search'
  get '/search', to: 'posts#index'

  get 'users/show'
  get '/notifications', to: 'users#notifications'
  get 'users/:id/notifications', to: 'users#notifications'
  get '/all_friends', to: 'users#all_friends'
  get 'users/:id/all_friends', to: 'users#all_friends'
  get 'posts/show'
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end
    unauthenticated :user do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  get 'pages/home'
  resources :users
  resources :posts
  resources :comments
  resources :likes
  resources :friendships
end

app/views/layouts/_header.html.erb
<header>
    
  <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <% if user_signed_in? %>
 
          <span><%= link_to "FACEBOOK CLONE", authenticated_root_path,id: "logo", class: "navbar-brand light-color"  %></span>

        <% else %>
  
          <%= link_to "FACEBOOK CLONE", unauthenticated_root_path,id: "logo", class: "navbar-brand light-color"  %>
        <% end %>
    
        <button type="button" class="navbar-toggle toggler" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span> 
        </button>
     
      </div>
    
      <div class="collapse navbar-collapse" id="myNavbar">
        <% if user_signed_in? %>
          <%= form_for :user, url: {controller: :users, action: 'search'}, method: :post, html: {class: "form-inline search-form", role:      "form"} do |s| %>
            <div class="form-group">
              <%= s.text_field :first_name, placeholder: "Name or Email", class: "form-control" %>
            </div>
            <%= s.submit "Search", class: "btn btn-primary" %>
          <% end %>
        <% end %>
  


        <ul class="nav navbar-nav navbar-right">
  
          <% if user_signed_in? %>
            <li class = "grava-link"> 
              <%= link_to profile_picture(current_user) %> 
              <%= link_to current_user.last_name, current_user %> 
            </li>
  
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Friends", all_friends_path %></li>
            <li><%= link_to "Notifications", notifications_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "LogOut", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %>
                </li>
              </ul>
            </li>
          <% else %>
    
            <%= render './shared/signin_form' %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>
</header>

app/views/layouts/_shim.html.erb
<%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">    
    

<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookClone</title>

    <%= render 'layouts/shim' %>
  </head>

  <body>
  <%= render './layouts/header' %>
  <div class="container">
  <% flash.each do |message_type, message| %>
     <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
   <% end %>
   
    <%= yield %>
  </div>
  </body>
</html>